---
# Install nova-compute packages
- apt: name=nova-compute state=present force=yes
- apt: name=sysfsutils state=present force=yes

- name: Copy nova.conf file
  template:
    src: nova.conf.j2
    dest: /etc/nova/nova.conf
    owner: nova
    group: nova
    mode: 0640

- name: Remove sqlite file
  file: path=/var/lib/nova/nova.sqlite state=absent
