---
- group: name=nova gid=113
- group: name=ceilometer gid=116
- group: name=libvirtd gid=114
- group: name=kvm gid=112

- user: name=nova uid=106 group=nova groups=libvirtd append=yes
- user: name=ceilometer uid=110 group=ceilometer
- user: name=libvirt-qemu uid=107 group=kvm

- name: Change Ubuntu default user's uid/gid to 2000
  command: bash -c "(grep ':1000:' /etc/group | grep -v rg > /dev/null) && groupmod -g 2000 $(grep 1000 /etc/group | awk -F ':' '{print $1}')"

- name: Add RG group as gid 1000
  group: name=rg gid=1000 state=present

- name: Change owner of Ubuntu defualt user directory to 2000 
  command: bash -c "chown -R :2000 /home/$(grep 2000 /etc/group | awk -F ':' '{print $1}')"
